YUI.add("yuidoc-meta", function(Y) {
   Y.YUIDoc = { meta: {
    "classes": [
        "API",
        "AnimationCancelor",
        "ApiOvertureComponent",
        "AvatarComponent3D",
        "BaseComponent2D",
        "BaseComponent3D",
        "BaseEditionComponent",
        "BaseStructure",
        "BaseTopMenuComponent2D",
        "CameraFeatures",
        "CurvedWall",
        "DataBundleComponent",
        "DecorationComponent",
        "DragComponent3D",
        "EditionComponent3D",
        "ExitComponent",
        "FirstPersonCamera",
        "FloorComponent3D",
        "FloorController",
        "FloorStructure",
        "FullscreenComponent",
        "Graph",
        "GraphComponent2D",
        "GraphComponent3D",
        "HardwareScalingComponent3D",
        "HistoryComponent",
        "HopperComponent2D",
        "HopperComponent3D",
        "HopperStructure",
        "LockComponent",
        "Logger",
        "LoopTimer",
        "MagnetismComponent3D",
        "MeasureComponent",
        "Menu",
        "MobileComponent",
        "MobileInputComponent",
        "NewComponent",
        "Object",
        "ObjectComponent3D",
        "OptionsComponent",
        "OrbitCamera",
        "Path",
        "PedagoComponent",
        "PerformanceComponent2D",
        "PointComponent2D",
        "PointStructure",
        "PolygonWall",
        "RoomComponent2D",
        "RoomComponent3D",
        "RoomEditorComponent",
        "RoomExampleComponent",
        "RoomHierarchy",
        "RoomStructure",
        "ScreenshotMenuComponent",
        "StairwayComponent2D",
        "TestManager",
        "WallComponent2D",
        "WallComponent3D",
        "WallStructure",
        "photonui.Base",
        "photonui.FileManager",
        "photonui.Helpers",
        "photonui.Widget",
        "subSlopeComponent2D",
        "subSlopeComponent3D",
        "wnp.AABB",
        "wnp.Action",
        "wnp.Advanced",
        "wnp.Angle",
        "wnp.Assets",
        "wnp.Asymetric",
        "wnp.BabyBed",
        "wnp.BabylonImporter",
        "wnp.Bar",
        "wnp.Base",
        "wnp.BaseBox",
        "wnp.Basic",
        "wnp.Bath",
        "wnp.BathTub",
        "wnp.Bed",
        "wnp.BenchIkea",
        "wnp.BetsideTable",
        "wnp.BureauTest",
        "wnp.BureauTestLarge",
        "wnp.Chair",
        "wnp.ChairHenriksdal",
        "wnp.ChairKritter",
        "wnp.CheneStoique",
        "wnp.CoffeeTableIkea",
        "wnp.ComponentCollection",
        "wnp.Configuration",
        "wnp.Constants",
        "wnp.Core",
        "wnp.Corner",
        "wnp.Curtains",
        "wnp.Cushion",
        "wnp.Dishes",
        "wnp.Dishwasher",
        "wnp.Door",
        "wnp.Dressing",
        "wnp.Dummy",
        "wnp.Engine2D",
        "wnp.Engine3D",
        "wnp.Fence",
        "wnp.FirePlace",
        "wnp.Furniture",
        "wnp.Garage",
        "wnp.GlassMaterial",
        "wnp.GridComponent2D",
        "wnp.GridComponent3D",
        "wnp.HistoryEditionComponent",
        "wnp.Hob",
        "wnp.Ilot",
        "wnp.Interval",
        "wnp.KeyboardManager",
        "wnp.Keys",
        "wnp.Kitchen",
        "wnp.LeatherMaterial",
        "wnp.Light",
        "wnp.LuxensMaterial",
        "wnp.MagnetismComponent2D",
        "wnp.MattMaterial",
        "wnp.MetalConsole",
        "wnp.MetalMaterial",
        "wnp.OBB",
        "wnp.OBJImporter",
        "wnp.Oven",
        "wnp.Overture",
        "wnp.OvertureStructure",
        "wnp.Ovoide",
        "wnp.OyBB",
        "wnp.PhotoFrame",
        "wnp.PlasticMaterial",
        "wnp.PointerManager",
        "wnp.Programmable",
        "wnp.RoundedTable",
        "wnp.RoundedTableFourFoot",
        "wnp.Shower",
        "wnp.Sink",
        "wnp.SinkBox",
        "wnp.Sofa",
        "wnp.SpotLamp",
        "wnp.Square",
        "wnp.Stairs",
        "wnp.Structure",
        "wnp.SubSlopeOvertureStructure",
        "wnp.Symbols2D",
        "wnp.Symetric",
        "wnp.Table",
        "wnp.TableBoconcept",
        "wnp.TableGeneric",
        "wnp.TableModer",
        "wnp.TableOvale",
        "wnp.TexturedMaterial",
        "wnp.TileMaterial",
        "wnp.TouchManager",
        "wnp.TowelDry",
        "wnp.Tv",
        "wnp.UI.AboutWindow",
        "wnp.UI.ContextMenu",
        "wnp.UI.FormBuilder",
        "wnp.UI.Frame",
        "wnp.UI.HelpBubble",
        "wnp.UI.HelpBubbleManager",
        "wnp.UI.MessageBox",
        "wnp.UI.Popup",
        "wnp.UI.RemoteController",
        "wnp.WhiteMaterial",
        "wnp.Window",
        "wnp.WoodMaterial",
        "wnp.bedstora",
        "wnp.chair",
        "wnp.chairiva",
        "wnp.cube",
        "wnp.cylinder",
        "wnp.hood",
        "wnp.overtureComponent2D",
        "wnp.overtureComponent3D",
        "wnp.plane",
        "wnp.sofacromwell",
        "wnp.spiralStairwayStructure",
        "wnp.spotMultiple",
        "wnp.stairwayComponent3D",
        "wnp.stairwayStructure",
        "wnp.straightStairwayStructure",
        "wnp.subSlopeOvertureComponent2D",
        "wnp.subSlopeStructure",
        "wnp.uuid"
    ],
    "modules": [
        "Component",
        "Core",
        "Helpers",
        "Input",
        "Misc",
        "PhotonUI",
        "Programmable",
        "UI",
        "Wanaplan"
    ],
    "allModules": [
        {
            "displayName": "Component",
            "name": "Component",
            "description": "Composant d'édition de la scène et de ses objets\nIntercepte et peut modifier toutes les interactions avec la scène\nNécessaire dès que la scène est modifiable par l'utilisateur"
        },
        {
            "displayName": "Core",
            "name": "Core",
            "description": "Wanaplan Core."
        },
        {
            "displayName": "Helpers",
            "name": "Helpers",
            "description": "PhotonUI - Javascript Web User Interface."
        },
        {
            "displayName": "Input",
            "name": "Input",
            "description": "Gestion des entrées clavier."
        },
        {
            "displayName": "Misc",
            "name": "Misc",
            "description": "PhotonUI - Javascript Web User Interface."
        },
        {
            "displayName": "PhotonUI",
            "name": "PhotonUI",
            "description": "PhotonUI - Javascript Web User Interface."
        },
        {
            "displayName": "Programmable",
            "name": "Programmable",
            "description": "Définit un objet 3D porte construit procéduralement."
        },
        {
            "displayName": "UI",
            "name": "UI",
            "description": "Création d'un menu contextuel."
        },
        {
            "displayName": "Wanaplan",
            "name": "Wanaplan"
        }
    ]
} };
});